---
- name: UPDATE LOCALES && LOAD LOCALES | MANUALLY CONFIGURE TASK IF ERRORS APPEARS
  become: true
  ansible.builtin.shell: locale-gen ru_RU.utf8 ru_UA.utf8 && update-locale

- name: STOP POSTGRES
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: stopped

- name: EDITING POSTGRESQL.CONF
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ version }}/main/postgresql.conf
    regexp: '^[#\s]*{{ item.split()[0] }}'
    line: '{{ item }}'
  loop: "{{ postgres_conf_slave }}"

- name: "|===================================| WARNING |===================================|"
  ansible.builtin.pause:
    prompt: "Next command will delete ALL files at /var/lib/postgresql/{{ version }}/main/. Make sure you made backup. You wanna continue? (y/n)"
  register: confirmation

- name: SHUT DOWN
  meta: end_play
  when: "confirmation.user_input.lower() not in ['y', 'yes']"

- name: CLEAR OLD FILES
  become: true
  ansible.builtin.shell: "rm -rf /var/lib/postgresql/{{ version }}/main/*"

- name: START POSTGRES (1)
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: started

- name: CHECK REPLICATION WORK
  become: true
  ansible.builtin.shell: "sudo -u postgres PGPASSWORD={{ repl_password }} pg_basebackup -R -h {{ hostvars['host_1'].ansible_host }} -U {{ repl_user }} -D /var/lib/postgresql/{{ version }}/main -P"

- name: START POSTGRES (2)
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: CONFIGURATION OF MASTER SERVER FINISHED
  ansible.builtin.pause:
    seconds: 3