- name: INSTALL POSTGRES
  hosts: all
  gather_facts: false
  vars_files: inventory/global_vars.yml
  roles:
    - role: postgresql_install
      tags: [ postgresql_install ]

- name: CONFIGURE MASTER SERVER
  hosts: master_host
  gather_facts: false
  vars_files: inventory/global_vars.yml
  roles:
    - role: postgresql_replication_master
      tags: [ postgresql_replication_master ]

- name: CONFIGURE SLAVE SERVERS
  hosts: slave_hosts
  gather_facts: false
  vars_files: inventory/global_vars.yml
  roles:
    - role: postgresql_replication_slave
      tags: [ postgresql_replication_slave ]

- name: CHECK REPLICATION
  hosts: all
  gather_facts: false
  vars_files: inventory/global_vars.yml
  roles:
    - role: replication_check
      tags: [ replication_check ]